services:
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: build/api-gateway.dockerfile
    ports:
      - "443:44300"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REDIS_PASSWORD: ${API_GATEWAY_REDIS_PASSWORD}

  content:
    container_name: content
    build:
      context: content
      dockerfile: build/content.dockerfile
    ports:
      - "44301:44301"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_NAME}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      SEARCH_USERNAME: ${SEARCH_USERNAME}
      SEARCH_PASSWORD: ${SEARCH_PASSWORD}

  file-server:
    container_name: file-server
    build:
      context: file-server
      dockerfile: build/file-server.dockerfile
    ports:
      - "44302:44302"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./storage/photos/:/storage/photos/
      - ./storage/videos/:/storage/videos/

  redis:
    container_name: redis
    image: 'redis:7.2'
    ports:
      - "63790:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REDIS_PASSWORD: ${API_GATEWAY_REDIS_PASSWORD}
    command:
      /bin/sh -c "redis-server --requirepass ${API_GATEWAY_REDIS_PASSWORD}"
    volumes:
      - ./storage/databases/redis/:/var/lib/redis

  postgres:
    container_name: postgres
    image: 'postgres:16.0'
    ports:
      - "54320:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./storage/databases/postgres/:/var/lib/postgresql/data/

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${SEARCH_PASSWORD}
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - ./storage/databases/opensearch/:/usr/share/opensearch/data