apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: 192.168.1.34:5000/dopmaterial-content:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 44301
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "user_dopmaterial"
            - name: POSTGRES_PASSWORD
              value: "cxqsaz_dopmaterial_password_qqqwez"
            - name: POSTGRES_DB_NAME
              value: "dopmaterial"
            - name: POSTGRES_SSL_MODE
              value: "disable"
            - name: SEARCH_USERNAME
              value: "admin"
            - name: SEARCH_PASSWORD
              value: "@dop5329__mAteRiaLS"
---
apiVersion: v1
kind: Service
metadata:
  name: content
spec:
  type: NodePort
  ports:
    - port: 44301
      targetPort: 44301
      nodePort: 30002
  selector:
    app: content
