apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
        - name: file-server
          image: 192.168.1.34:5000/dopmaterial-file-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 44302
          volumeMounts:
            - name: storage-photos
              mountPath: /storage/photos/
            - name: storage-videos
              mountPath: /storage/videos/
      volumes:
        - name: storage-photos
          hostPath:
            path: /storage/photos/
        - name: storage-videos
          hostPath:
            path: /storage/videos/
---
apiVersion: v1
kind: Service
metadata:
  name: file-server
spec:
  type: LoadBalancer
  ports:
    - port: 44302
      targetPort: 44302
  selector:
    app: file-server
